services:
  postgres-db:
    image: postgres:15-alpine
    container_name: autodrive-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autodrive-network

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autodrive-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AUTODRIVE_APP_JWTSECRET=${JWT_SECRET}
      - AUTODRIVE_APP_JWTEXPIRATIONMS=${JWT_EXPIRATION}
    depends_on:
      - postgres-db
    networks:
      - autodrive-network

volumes:
  postgres_data:

networks:
  autodrive-network: